### ISSUE TITLE
How to catch Sax errors?

### ISSUE THREAD

**Issue by OliverJAsh** [danmactough/node-feedparser#109]
Sometimes I get sax errors. How can I catch them?

I have kept `resume_saxerror` to its default value of `true`.

```
Error: Unexpected end
Line: 543
Column: 146
Char:
                at error (/Users/Oliver/Development/sbscribe/sbscribe-common/node_modules/feedparser/node_modules/sax/lib/sax.js:642:8)
                at end (/Users/Oliver/Development/sbscribe/sbscribe-common/node_modules/feedparser/node_modules/sax/lib/sax.js:650:64)
                at SAXParser.end (/Users/Oliver/Development/sbscribe/sbscribe-common/node_modules/feedparser/node_modules/sax/lib/sax.js:149:24)
                at SAXStream.end (/Users/Oliver/Development/sbscribe/sbscribe-common/node_modules/feedparser/node_modules/sax/lib/sax.js:234:16)
                at FeedParser._flush (/Users/Oliver/Development/sbscribe/sbscribe-common/node_modules/feedparser/main.js:1012:17)
                at FeedParser.<anonymous> (_stream_transform.js:130:12)
                at g (events.js:180:16)
                at EventEmitter.emit (events.js:92:17)
```

**Comment by danmactough** [comment]
Closed (I think) via #302
